version: '3.8'
services:
  db:
      image: mysql:8.1.0
      volumes:
        - ./database:/var/lib/mysql
      restart: unless-stopped
      ports:
        - "3306:3306"
      env_file:
        .env
  backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - db
      env_file:
        - .env
      restart: unless-stopped
